import React, { useEffect } from "react";
import { useTranslation } from "react-i18next";
import NewsTable from "../../table/newsTable/newsTable";
import { useRecoilState } from "recoil";
import { cryptoNews } from "../../../atoms/cryptoNews";

export default function News() {
  const { t } = useTranslation();
  const [cryptoCurrenciesNews, setCryptoCurrenciesNews] =
    useRecoilState(cryptoNews);

  const mockNews = [
    {
      id: "23857346",
      guid: "https://coingape.com/?p=177570",
      published_on: 1709223954,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title: "7 Best Cryptocurrency Futures Trading Platforms in 2024",
      url: "https://coingape.com/best-cryptocurrency-futures-trading-platforms/",
      body: "Crypto futures trading allows traders to predict future price movements and enter agreements to buy or sell assets at predetermined prices on future dates. However, it calls for traders to address and stay strong in the market with higher crypto volatility. In this segment, each market fluctuation becomes an opportunity – and whether you make The post 7 Best Cryptocurrency Futures Trading Platforms in 2024 appeared first on CoinGape .",
      tags: "Top",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "TRADING|MARKET",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23857348",
      guid: "https://coingape.com/?p=183309",
      published_on: 1709223954,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title: "Bonk Crypto Price Prediction: Whales Set Sight on New ATH",
      url: "https://coingape.com/bonk-crypto-price-prediction-whales-set-sight-on-new-ath/",
      body: "In an intriguing turn of events, aligning with the bullish sentiment prevailing within the broader crypto market, Bonk, a meme coin, gained significant traction across the global crypto realm as it surged nearly 30% today, February 29. This surge by the meme coin promptly garnered noteworthy attention as a Smart Money’s accumulation, pushing the price The post Bonk Crypto Price Prediction: Whales Set Sight on New ATH appeared first on CoinGape .",
      tags: "24/7 Cryptocurrency News|Altcoin News|Bonk (BONK)",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "TRADING|MARKET",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23857807",
      guid: "https://coingape.com/?post_type=trending&p=183305",
      published_on: 1709223850,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title: "Binance (BNB) Introduced VIP Programs For Non-Crypto Traders",
      url: "https://coingape.com/trending/binance-bnb-introduced-vip-programs-for-non-crypto-traders/",
      body: "Binance is the largest centralized exchange according to the trading volume and has its native token. To expand its reach, Binance has taken one more step, introducing the VIP program. This blog will cover ‘what is this VIP program and how it will affect the BNB prices.’ Understanding the Binance (BNB) VIP Program Binance has The post Binance (BNB) Introduced VIP Programs For Non-Crypto Traders appeared first on CoinGape .",
      tags: "24/7 Cryptocurrency News|Binance (BNB) Coin|binance lawsuit|trending news",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "EXCHANGE|ICO|TRADING",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23861209",
      guid: "https://coingape.com/?post_type=trending&p=183366",
      published_on: 1709223850,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title: "Top Reasons Why Ethereum Price Might Hit $4000 In March",
      url: "https://coingape.com/trending/top-reasons-why-ethereum-might-hit-4000-in-march/",
      body: "Ethereum has performed exceptionally well in the last few days and is trading at $3,479.70 after crossing the $3500 mark a few hours ago. Ethereum gained a significant hike this month after strangling below $3000 for months. One question that comes to mind is whether Ethereum will be able to hit $4k or it won’t. The post Top Reasons Why Ethereum Price Might Hit $4000 In March appeared first on CoinGape .",
      tags: "24/7 Cryptocurrency News|Ethereum (ETH)|Ethereum Price Prediction|Ethereum Surge",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "ETH|TRADING",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23859336",
      guid: "https://coingape.com/?post_type=markets&p=183363",
      published_on: 1709223850,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title: "What’s Next As Bonk Crypto Price Soars 35% Alongside Pepe, SHIB",
      url: "https://coingape.com/markets/whats-next-as-bonk-crypto-price-soars-35-alongside-pepe-shib/",
      body: "Bonk crypto price analysis: BONK, a dog-themed digital currency based on the Solana network, has recently experienced a remarkable upswing in market activity. Over the past 24 hours, Bonk price has soared by more than 35%, reaching a new high of $0.00002223. This impressive growth has pushed Bonk’s total market value over $1.44 billion. As The post What’s Next As Bonk Crypto Price Soars 35% Alongside Pepe, SHIB appeared first on CoinGape .",
      tags: "Price Analysis|Bonk (BONK)|BONK price analysis|BONK price prediction",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "TRADING|MARKET|SHIB|SOL",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23857760",
      guid: "https://coingape.com/?post_type=markets&p=183335",
      published_on: 1709223702,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title:
        "Bitcoin, Ethereum, Solana Crypto Price Prediction: Is The ETF Rally On Course To $70,000?",
      url: "https://coingape.com/markets/crypto-price-prediction/",
      body: "Bitcoin’s surprise move on Wednesday from a low of $56,738 to $63,913 sparked widespread price increases among altcoins with Ethereum (ETH) leading the charge to $3,500. Based on the latest crypto price prediction, both fundamentals and technical levels are strong for a continued rally towards the all-time high near $70,000 and BTC’s eventual climb above $70,000. The post Bitcoin, Ethereum, Solana Crypto Price Prediction: Is The ETF Rally On Course To $70,000? appeared first on CoinGape .",
      tags: "Price Analysis|Bitcoin|Bitcoin News|Crypto price today|Ethereum (ETH)|Ethereum News|solana",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "TRADING|BTC|ETH|SOL|ALTCOIN",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23857030",
      guid: "https://coingape.com/?post_type=markets&p=183316",
      published_on: 1709223560,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title: "5 DePIN Crypto To Buy Matching Up To Bitcoin’s Pre-Halving Run",
      url: "https://coingape.com/markets/5-depin-crypto-to-buy-matching-up-to-bitcoins-pre-halving-run/",
      body: "The DePINs are making waves in the crypto to buy sphere as they blend blockchain with real-world infrastructure, offering a fresh perspective on technology’s capabilities. With Bitcoin’s value on the rise and Bitcoin halving event on the horizon, DePINs like Filecoin (FIL), Render (RNDR), Arweave (AR), Theta Network (THETA), and Akash Network (AKT) are capturing The post 5 DePIN Crypto To Buy Matching Up To Bitcoin’s Pre-Halving Run appeared first on CoinGape .",
      tags: "Price Analysis|Bitcoin (BTC) Price|Bitcoin Halving|FIL|Render (RNDR)|THETA",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "BTC|FIL|BLOCKCHAIN|ICO|TECHNOLOGY",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23860471",
      guid: "https://coingape.com/?post_type=markets&p=183372",
      published_on: 1709223407,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title:
        "Shiba Inu Coin Price Prediction: Why SHIB Could Peak At $0.0001 In March?",
      url: "https://coingape.com/markets/shiba-inu-coin-price-prediction-why-shib-could-peak-at-0-0001-in-march/",
      body: "Shiba Inu Coin, the second most prominent meme coin, has been on the move this week, rallying in tandem with Bitcoin. As BTC peaked close to $64,000 on Wednesday, SHIB topped out at $0.0000147. Shiba Inu Coin price is up by a staggering 135% from its 2023 low of $0.0000059 to trade at $0.000014 during US The post Shiba Inu Coin Price Prediction: Why SHIB Could Peak At $0.0001 In March? appeared first on CoinGape .",
      tags: "",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "SHIB|TRADING|BTC",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23861132",
      guid: "https://finbold.com/?p=157960",
      published_on: 1709223404,
      imageurl: "https://images.cryptocompare.com/news/default/finbold.png",
      title: "4 cryptocurrencies to turn $10 into $100 next week",
      url: "https://finbold.com/4-cryptocurrencies-to-turn-10-into-100-next-week/",
      body: "With the current week at its end, it has demonstrated exciting moves in the cryptocurrency sphere, which have seen Bitcoin … Continue reading The post 4 cryptocurrencies to turn $10 into $100 next week appeared first on Finbold .",
      tags: "Cryptocurrency news|ADA|Cardano|Litecoin|LTC|SHIB|Shiba Inu|verasity|VRA",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "ADA|LTC|SHIB|BTC",
      source_info: {
        name: "Finbold",
        img: "https://images.cryptocompare.com/news/default/finbold.png",
        lang: "EN",
      },
      source: "finbold",
    },
    {
      id: "23861133",
      guid: "https://en.coin-turk.com/?p=133687",
      published_on: 1709223379,
      imageurl: "https://resources.cryptocompare.com/news/79/23861133.jpeg",
      title: "BlackRock Launches Bitcoin ETF in Brazil",
      url: "https://en.coin-turk.com/blackrock-launches-bitcoin-etf-in-brazil/",
      body: "Spot Bitcoin ETFs trigger Bitcoin's continued rise, now in Brazil. BlackRock's iShares Bitcoin Trust ETF debuts with Brazil's B3. Continue Reading: BlackRock Launches Bitcoin ETF in Brazil",
      tags: "Bitcoin (BTC)",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "BTC",
      source_info: {
        name: "CoinTurk News",
        img: "https://resources.cryptocompare.com/news/79/default.png",
        lang: "EN",
      },
      source: "cointurken",
    },
    {
      id: "23861164",
      guid: "https://u.today/shib-lead-shytoshi-kusama-spotted-in-denver-heres-why-its-important",
      published_on: 1709223300,
      imageurl: "https://resources.cryptocompare.com/news/64/23861164.jpeg",
      title:
        "SHIB Lead Shytoshi Kusama Spotted in Denver, Here’s Why It’s Important",
      url: "https://u.today/shib-lead-shytoshi-kusama-spotted-in-denver-heres-why-its-important",
      body: "The Shiba Inu lead has again changed his location status on Twitter/X, raising SHIB army’s curiosity",
      tags: "Shytoshi Kusama",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "SHIB",
      source_info: {
        name: "U.Today",
        img: "https://images.cryptocompare.com/news/default/utoday.png",
        lang: "EN",
      },
      source: "utoday",
    },
    {
      id: "23861211",
      guid: "https://zycrypto.com/?p=88361",
      published_on: 1709223294,
      imageurl: "https://images.cryptocompare.com/news/default/zycrypto.png",
      title:
        "Bitcoin Whale Addresses Go Through The Roof After Recording Fastest Growth Rate in 2 Years",
      url: "https://zycrypto.com/bitcoin-whale-addresses-go-through-the-roof-after-recording-fastest-growth-rate-in-2-years/",
      body: "As all-time high (ATH) chats continue taking center stage in the crypto market, thanks to Bitcoin hitting a 27-month high above the $63,000 level, BTC whales are not relenting on their quest to continue accumulating.",
      tags: "Bitcoin|News|Bitcoin News|BTCUSD|BTCUSDC|BTCUSDT|Cryptocurrency News|XBTUSD",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "BTC|MARKET",
      source_info: {
        name: "ZyCrypto",
        img: "https://images.cryptocompare.com/news/default/zycrypto.png",
        lang: "EN",
      },
      source: "zycrypto",
    },
    {
      id: "23861126",
      guid: "https://www.theblock.co/post/279785",
      published_on: 1709223290,
      imageurl: "https://images.cryptocompare.com/news/default/theblock.png",
      title:
        "Bitcoin closes in on posting the biggest monthly candle in its history",
      url: "https://www.theblock.co/post/279785/bitcoin-closes-in-on-posting-the-biggest-monthly-candle-in-its-history?utm_source=cryptocompare&utm_medium=rss",
      body: "Bitcoin is set to close February posting a gain of almost $20,000 since the beginning of the month, according to Coingecko data.",
      tags: "Funds|Market Recap|Market Updates|Markets|The Block|Crypto Movers|Spot Bitcoin ETF",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "BTC|MARKET",
      source_info: {
        name: "TheBlock",
        img: "https://images.cryptocompare.com/news/default/theblock.png",
        lang: "EN",
      },
      source: "theblock",
    },
    {
      id: "23858141",
      guid: "https://coingape.com/?p=183334",
      published_on: 1709223254,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title: "Bitcoin Rally as US PCE Cools to 2.4%, Fed Rate Cuts in June",
      url: "https://coingape.com/bitcoin-rally-continue-us-pce-cools-2-4-fed-rate-cuts-likely-june/",
      body: "The U.S. Bureau of Economic Analysis announced the U.S. Federal Reserve’s (Fed) preferred inflation gauge PCE data for January. The PCE in the US went up 0.3% month-over-month in January, the most in four months, following a 0.2% rise in December. Also, the monthly core PCE index, which excludes food and energy, rise to 0.4%, the The post Bitcoin Rally as US PCE Cools to 2.4%, Fed Rate Cuts in June appeared first on CoinGape .",
      tags: "24/7 Cryptocurrency News|Bitcoin News|Bitcoin (BTC) Price|US Inflation",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "BTC|MARKET|TRADING|FIAT",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23860453",
      guid: "https://coingape.com/?p=183370",
      published_on: 1709223141,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title: "Will Cardano Join Solana on Brave? Charles Hoskinson Anticipate",
      url: "https://coingape.com/will-cardano-join-solana-on-brave-charles-hoskinson-anticipate/",
      body: "The Cardano (ADA) community, led by its founder Charles Hoskinson, has initiated a campaign to integrate its blockchain with the Brave Browser, signaling a strategic move to enhance its visibility and adoption. Hoskinson has rallied his substantial social media following with a voting campaign underway on the Brave Community platform, urging over 978,600 followers on The post Will Cardano Join Solana on Brave? Charles Hoskinson Anticipate appeared first on CoinGape .",
      tags: "24/7 Cryptocurrency News|Cardano|Charles Hoskinson|solana",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "ADA|SOL|BLOCKCHAIN",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23859820",
      guid: "https://coingape.com/?p=183091",
      published_on: 1709223045,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title: "15 Best Metamask Alternatives",
      url: "https://coingape.com/metamask-alternatives/",
      body: "People are now seeking even more advanced technology, and the credit goes to the advent of blockchain technology. As a result of this development, numerous payment options—including wallets for cryptocurrencies—are now available. In this article, we will be talking about crypto wallets while comparing them to the most popular one, i.e., Metamask. Have a look: The post 15 Best Metamask Alternatives appeared first on CoinGape .",
      tags: "Top|Wallets",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "TECHNOLOGY|BLOCKCHAIN",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23861039",
      guid: "https://www.cryptopolitan.com/?p=475276",
      published_on: 1709223030,
      imageurl: "https://resources.cryptocompare.com/news/43/23861039.jpeg",
      title: "Crypto markets on high FOMO alert – Here’s what’s happening",
      url: "https://www.cryptopolitan.com/crypto-markets-on-high-fomo-alert/",
      body: "The crypto markets are currently experiencing heightened levels of FOMO (Fear of Missing Out), leading to significant volatility and speculative trading activity. FOMO in crypto refers to the fear investors feel when they perceive they are missing out on potential profits. Here’s what’s happening: Crypto markets shift to extreme greed The crypto market often experiences",
      tags: "Industry News|News|Bitcoin Bull run|Bull rally|fomo|FUD",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "MARKET|BUSINESS|TRADING",
      source_info: {
        name: "Cryptopolitan",
        img: "https://images.cryptocompare.com/news/default/cryptopolitan.png",
        lang: "EN",
      },
      source: "cryptopolitan",
    },
    {
      id: "23856568",
      guid: "https://coingape.com/?p=183291",
      published_on: 1709222944,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title:
        "Bitcoin Crash: Key Reasons Behind BTC Retreat After Rallying To $64K",
      url: "https://coingape.com/bitcoin-crash-key-reasons-behind-btc-retreat-after-rallying-to-64k/",
      body: "The Bitcoin crash, after a rally to the $64,000 mark, has stirred both excitement and concerns in the crypto space. The Bitcoin price retreat after hitting nearly $64K on Wednesday has sparked speculations in the crypto market. Meanwhile, the Bitcoin price has crossed the $60,000 mark for the first time since November 2021 and was The post Bitcoin Crash: Key Reasons Behind BTC Retreat After Rallying To $64K appeared first on CoinGape .",
      tags: "24/7 Cryptocurrency News|Bitcoin News|Bitcoin|Bitcoin (BTC) Price|Coinbase Crash|Crypto Liquidation",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "BTC|TRADING|MARKET",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23859792",
      guid: "https://coingape.com/?p=183342",
      published_on: 1709222944,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title:
        "Binance Recovers $4.4 Billion Worth of Users’ Mishandled Digital Assets",
      url: "https://coingape.com/binance-recovers-4-4-billion-worth-of-users-mishandled-digital-assets/",
      body: "Binance declared that it had recovered digital assets that had previously been improperly handled by a user. According to a Bloomberg report, assets worth over $4 billion had been retrieved for a user who has mishandled their account for the past two years. The announcement comes at a point when Binance is already undergoing issues The post Binance Recovers $4.4 Billion Worth of Users’ Mishandled Digital Assets appeared first on CoinGape .",
      tags: "24/7 Cryptocurrency News|Binance|digital asset",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "EXCHANGE",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23860950",
      guid: "https://coingape.com/?p=183375",
      published_on: 1709222843,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title: "Coinbase, MicroStrategy Shares Rally As PCE Inflation Cools 2.4%",
      url: "https://coingape.com/coinbase-microstrategy-shares-rally-as-pce-inflation-cools-2-4/",
      body: "Amidst the slowdown in the United States consumer price increase, American publicly traded exchange Coinbase and other crypto-linked stocks like Michael Saylor’s MicroStrategy are on track to end February on a very good note. Decline in US Inflation Rate According to a report from the U.S. government, prices moved 0.3% from December to January, indicating The post Coinbase, MicroStrategy Shares Rally As PCE Inflation Cools 2.4% appeared first on CoinGape .",
      tags: "24/7 Cryptocurrency News|Coinbase|microstrategy",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "TRADING|EXCHANGE|MARKET",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23857574",
      guid: "https://coingape.com/?p=183304",
      published_on: 1709222843,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title:
        "Telegram Addresses Toncoin (TON) Supply Concerns Amid Ad Platform Launch",
      url: "https://coingape.com/telegram-addresses-toncoin-ton-supply-concerns-amid-ad-platform-launch/",
      body: "In response to growing concerns about the concentration of Toncoin (TON) supply within Telegram’s ecosystem, CEO and Founder Pavel Durov has unveiled a proactive strategy aimed at maintaining decentralization and stability. This announcement comes as Telegram prepares to launch its long-awaited advertising platform, marking a significant milestone in the platform’s evolution. Telegram CEO Eases Toncoin The post Telegram Addresses Toncoin (TON) Supply Concerns Amid Ad Platform Launch appeared first on CoinGape .",
      tags: "24/7 Cryptocurrency News|Altcoin News|telegram|TON|Toncoin",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "OTHER",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23860963",
      guid: "https://www.cryptopolitan.com/?p=475157",
      published_on: 1709222825,
      imageurl: "https://resources.cryptocompare.com/news/43/23860963.jpeg",
      title:
        "Sega Bolsters Transmedia Strategy with Industry Veteran Justin Scarpone",
      url: "https://www.cryptopolitan.com/sega-bolsters-transmedia-strategy-with-industry-veteran-justin-scarpone/",
      body: "In a strategic move to enhance its presence across various media platforms, Sega has announced the appointment of Justin Scarpone, a former Disney and Scopely executive, as the new executive vice president and global head of transmedia. This appointment, set to take effect on April 1, 2024, signifies Sega’s commitment to expanding its intellectual property",
      tags: "Industry News",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "REGULATION",
      source_info: {
        name: "Cryptopolitan",
        img: "https://images.cryptocompare.com/news/default/cryptopolitan.png",
        lang: "EN",
      },
      source: "cryptopolitan",
    },
    {
      id: "23860964",
      guid: "https://crypto.news/?p=14253896",
      published_on: 1709222819,
      imageurl: "https://resources.cryptocompare.com/news/73/23860964.jpeg",
      title: "Bitcoin CEX trading volume hits highest level since 2022",
      url: "https://crypto.news/bitcoin-trading-volume-2024/",
      body: "Bitcoin spot trading volumes on centralized exchanges returned to peaks last seen when FTX crashed amid daily sustained demand for ETFs investing in crypto’s top currency.",
      tags: "News|Bitcoin|CEX|Spot Bitcoin ETF|Trading",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "BTC|TRADING",
      source_info: {
        name: "crypto.news",
        img: "https://resources.cryptocompare.com/news/73/default.png",
        lang: "EN",
      },
      source: "crypto_news",
    },
    {
      id: "23860934",
      guid: "https://www.cryptopolitan.com/?p=475256",
      published_on: 1709222743,
      imageurl: "https://resources.cryptocompare.com/news/43/23860934.jpeg",
      title:
        "Australia Post Embarks on Digital Transformation with Salesforce Partnership",
      url: "https://www.cryptopolitan.com/australia-post-transformation-salesforce/",
      body: "In a significant move towards digital modernization, Australia Post has announced a multi-year collaboration with Salesforce, the global leader in Customer Relationship Management (CRM). This partnership is set to redefine the customer experience across Australia Post’s vast network, leveraging Salesforce’s advanced data and Artificial Intelligence (AI) capabilities. The initiative underscores Australia Post’s commitment to enhancing",
      tags: "AI|Trending News",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "OTHER",
      source_info: {
        name: "Cryptopolitan",
        img: "https://images.cryptocompare.com/news/default/cryptopolitan.png",
        lang: "EN",
      },
      source: "cryptopolitan",
    },
    {
      id: "23859001",
      guid: "https://coingape.com/?p=183358",
      published_on: 1709222735,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title:
        "Dogecoin Whales Shift 762 Mln DOGE As Price Tops $0.1, What’s Next?",
      url: "https://coingape.com/dogecoin-whales-shift-762-mln-doge-price-tops-0-1-whats-next/",
      body: "Dogecoin, one of the most prominent meme coins trading within the cryptocurrency landscape, again sparked immense optimism among crypto market enthusiasts across the globe as its price rallied nearly 30% today, February 29. Amid this phenomenal rally, insights revealed by the blockchain tracker Whale Alert revealed a staggering 761.2 million DOGE on the move, piquing The post Dogecoin Whales Shift 762 Mln DOGE As Price Tops $0.1, What’s Next? appeared first on CoinGape .",
      tags: "24/7 Cryptocurrency News|Altcoin News|Dogecoin (DOGE)|Whale transaction",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "DOGE|TRADING|BLOCKCHAIN|MARKET",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23860933",
      guid: "https://www.cryptopolitan.com/?p=475266",
      published_on: 1709222692,
      imageurl: "https://resources.cryptocompare.com/news/43/23860933.jpeg",
      title: "Bitcoin ETFs rattle Wall Street as BTC crosses $63K",
      url: "https://www.cryptopolitan.com/bitcoin-etfs-rattle-wall-street-btc-at-63k/",
      body: "The emergence of Bitcoin ETFs has rattled Wall Street, stirring both excitement and concern. While some view ETFs as a gateway to broader adoption and legitimacy for BTC, others raise concerns about potential market manipulation and regulatory challenges. The introduction and approval of Bitcoin ETFs have intensified interest and apprehension among Wall Street investors and",
      tags: "ETFs|News|bitcoin|Bitcoin ETFs|Bull run",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "BTC|BUSINESS|ICO|MARKET",
      source_info: {
        name: "Cryptopolitan",
        img: "https://images.cryptocompare.com/news/default/cryptopolitan.png",
        lang: "EN",
      },
      source: "cryptopolitan",
    },
    {
      id: "23860219",
      guid: "https://coingape.com/?p=183369",
      published_on: 1709222640,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title: "SEC Reviews NYSE Plan for Bitcoin ETF Options Trading",
      url: "https://coingape.com/sec-reviews-nyse-plan-for-bitcoin-etf-options-trading/",
      body: "The Securities and Exchange Commission (SEC) has announced the filing of a proposed rule change by NYSE American LLC. This modification, identified under Amendment No. 2, aims to adjust Rule 915 to enable the listing and trading of options on specific Bitcoin-related investment products. These products include the Bitwise Bitcoin ETF, the Grayscale Bitcoin Trust The post SEC Reviews NYSE Plan for Bitcoin ETF Options Trading appeared first on CoinGape .",
      tags: "24/7 Cryptocurrency News|Regulation News|Bitcoin ETF|Securities and Exchange Commission",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "BTC|REGULATION|TRADING|EXCHANGE",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23857556",
      guid: "https://coingape.com/?p=183286",
      published_on: 1709222544,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title:
        "Terra Luna Classic Reaches 100 Billion LUNC Burn Landmark, LUNC Price Jumps 10%",
      url: "https://coingape.com/terra-luna-classic-reaches-100-billion-lunc-burn-landmark-lunc-price-jumps-10/",
      body: "Terra Luna Classic community’s campaign to reduce LUNC supply through token burn has hit the 100 billion LUNC landmark. The world’s largest crypto exchange Binance has contributed immensely to LUNC burn with its monthly LUNC burn mechanism, accounting for over 51% of the total LUNC burned by the community. The community currently awaits Binance’s 19th The post Terra Luna Classic Reaches 100 Billion LUNC Burn Landmark, LUNC Price Jumps 10% appeared first on CoinGape .",
      tags: "24/7 Cryptocurrency News|Altcoin News|Binance|Terra (LUNA)|Terra Classic",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "LUNC|EXCHANGE|TRADING|ICO",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23861069",
      guid: "https://invezz.com/?p=1525738",
      published_on: 1709222510,
      imageurl: "https://resources.cryptocompare.com/news/69/default.png",
      title:
        "Why Polygon (MATIC) could steal the show in 2024: zero inflation, airdrops, & more",
      url: "https://invezz.com/news/2024/02/29/why-polygon-matic-could-steal-the-show-in-2024-zero-inflation-airdrops-more/",
      body: "Polygon’s MATIC is among the cryptos poised for massive surges this year, with various optimistic facets at play. The project ended inflation within the ecosystem after releasing all tokens into circulation last week. Moreover, Polygon is an Ethereum Layer2 solution, and its latest developments amidst surging interest in L2 networks are setting a platform for",
      tags: "Altcoins|Blockchain|Crypto|Crypto business|Inflation|[object Object]",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "MATIC|ALTCOIN|BLOCKCHAIN|ETH|ICO",
      source_info: {
        name: "Invezz",
        img: "https://resources.cryptocompare.com/news/69/default.png",
        lang: "EN",
      },
      source: "invezz",
    },
    {
      id: "23858914",
      guid: "https://coingape.com/?p=183359",
      published_on: 1709222449,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title: "ETH Targets $4K as Investors Stash $2.1B for the Long Haul",
      url: "https://coingape.com/eth-targets-4k-as-investors-stash-2-1b-for-the-long-haul/",
      body: "Ethereum has seen a surge in its market performance, largely attributed to significant catalysts driving investor sentiment. The successful execution of the Dencun upgrade testnet and the increasing interest in ETH ETF filings have fueled Ethereum’s bullish trajectory. Notably, there has been a notable shift in the investment horizon of Ethereum stakeholders towards long-term holding The post ETH Targets $4K as Investors Stash $2.1B for the Long Haul appeared first on CoinGape .",
      tags: "24/7 Cryptocurrency News|Altcoin News|ETH price|Ethereum (ETH)|Ethereum price",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "ETH|BUSINESS|MARKET|TRADING",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23860791",
      guid: "https://www.newsbtc.com/?p=590699",
      published_on: 1709222419,
      imageurl: "https://images.cryptocompare.com/news/default/newsbtc.png",
      title: "Shiba Inu (SHIB) Price Skyrockets By 28%: 4 Key Reasons",
      url: "https://www.newsbtc.com/shiba-inu/shiba-inu-shib-price-skyrockets-by-28-4-key-reasons/",
      body: "The price of Shiba Inu (SHIB) has surged by 28% in the last 24 hours and 45% in the last seven days. Today’s surge can be attributed to a confluence of factors, including a rekindling meme coin frenzy, actions by crypto whales, a favorable chart setup, and significant partnerships and ecosystem expansions. Here’s an in-depth look at these pivotal elements fueling SHIB’s impressive rally. #1 Meme Coin Frenzy In the wake of yesterday’s significant Bitcoin surge, there’s seemingly a noticeable resurgence of interest in higher-risk investments within the crypto sphere. An examination of the most recent 24-hour performance data reveals that the top three performers among the top 100 cryptocurrencies, measured by market capitalization, are all meme coins. Leading the pack is BONK with an impressive 52% gain, followed by Dogecoin with a 33% increase, and SHIB rounding out the trio with a 25% rise. This trend suggests that we may be on the cusp of another meme coin rally. Crypto analyst Rekt Capital has contributed to this narrative by sharing a chart depicting the total market capitalization of altcoins, excluding the top 10. His analysis, encapsulated by the remark, “ALTS Altcoin Market Cap is on the right track,” highlights a breakthrough past a significant resistance level. The market is now poised to target a $315.57 billion valuation, currently standing at approximately $272 billion. $ALTS Altcoin Market Cap is on the right track#BTC #Crypto #Bitcoin pic.twitter.com/wNJ7grLbFl — Rekt Capital (@rektcapital) February 29, 2024 #2 Whale Movements A notable development that has captured the crypto community’s attention is that a whale has made significant moves within the meme coin market, particularly with Shiba Inu (SHIB) and Pepe (PEPE). These transactions came to light through the analysis of Lookonchain, which detailed the whale’s manoeuvres on social media. Related Reading: Here Are The Factors Driving The Shiba Inu Recovery Above $0.00001 According to Lookonchain’s insights, this unidentified investor transferred an eye-catching 1.97 trillion PEPE tokens, valued at around $6.07 million, to Binance. This strategic shift yielded a profit of $3.49 million, showcasing the investor’s adept timing and market navigation skills. Subsequently, capitalizing on this lucrative outcome, the whale pivoted towards Shiba Inu, withdrawing 75.9 billion SHIB tokens—equivalent to $893,000—from Binance mere hours later. #3 Chart Setup Another contributing factor might have been a bullish pattern for SHIB which emerged three weeks ago, foreshadowing a potential upturn in its market trajectory. Since mid-December 2023, SHIB’s price movement has been characterized by a descending parallel channel. Related Reading: Shiba Inu: Shibarium Transaction Activity Spike Amid Market Growth A pivotal moment came on February 7, when SHIB broke free from this channel, surpassing the 200-day Exponential Moving Average (EMA) and subsequently breaching the 20- and 50-week EMAs. This development has set the stage for the current rally. This breakout is of particular interest because it reflects a similar pattern observed in October 2023, when SHIB experienced a breakout from a descending channel, leading to an almost 80% increase in its value over the span of 59 days. Should the SHIB market replicate this historical performance, the target might be set at the 0.786 Fibonacci retracement level, priced at $0.00001525. Achieving this would represent a significant rally of approximately 73%. #4 Partnerships and Expanding Ecosystem Yesterday, the SHIB team announced a partnership with Zama, a leader in Fully Homomorphic Encryption (FHE) technology. This collaboration aims to enhance the privacy and security features of the SHIB ecosystem. Zama’s expertise in cryptography and FHE will enable SHIB to process data in its encrypted state, ensuring user privacy and data protection. This strategic alliance not only fortifies the ecosystem’s security but also showcases SHIB’s commitment to innovation and user trust. Shiba Inu lead developer Shytoshi Kusama remarked: Our latest partnership is a BIG one. Pay close attention to why Encryption and Privacy are important to the Shib Ecosystem and state! SHIB has recently been very active in entering into new partnerships. Most recently, K9 Finance was accepted into the SHIB army. Overall, the combination of resurging interest in meme coins, strategic investments by crypto whales, a favorable chart setup, and impactful partnerships have probably collectively fueled SHIB’s price surge. Featured image created with DALLE, chart from TradingView.com",
      tags: "Shiba Inu|SHIB|SHIB price|shiba inu coin|Shiba Inu news|Shiba Inu Price|SHIBUSD",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "SHIB|MARKET|TRADING|ALTCOIN|BUSINESS",
      source_info: {
        name: "NewsBTC",
        img: "https://images.cryptocompare.com/news/default/newsbtc.png",
        lang: "EN",
      },
      source: "newsbtc",
    },
    {
      id: "23860821",
      guid: "https://thecoinrise.com/?p=92896",
      published_on: 1709222406,
      imageurl: "https://resources.cryptocompare.com/news/60/23860821.jpeg",
      title:
        "NuggetRush Shows Unmatched Resilience as Internet Computer and Toncoin Struggle to Maintain Momentum",
      url: "https://thecoinrise.com/nuggetrush-shows-unmatched-resilience-as-internet-computer-and-toncoin-struggle-to-maintain-momentum/",
      body: "NuggetRush demonstrates unparalleled stability as Internet Computer and Toncoin face challenges in maintaining their pace The post NuggetRush Shows Unmatched Resilience as Internet Computer and Toncoin Struggle to Maintain Momentum appeared first on Latest News and Insights on Blockchain, Cryptocurrency, and Investing .",
      tags: "Token Presale and ICO Insights|NuggetRush",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "BLOCKCHAIN",
      source_info: {
        name: "The Coin Rise",
        img: "https://images.cryptocompare.com/news/default/thecoinrise.png",
        lang: "EN",
      },
      source: "thecoinrise",
    },
    {
      id: "23860866",
      guid: "https://u.today/ethereum-eth-price-prediction-for-february-29",
      published_on: 1709222400,
      imageurl: "https://resources.cryptocompare.com/news/64/23860866.jpeg",
      title: "Ethereum (ETH) Price Prediction for February 29",
      url: "https://u.today/ethereum-eth-price-prediction-for-february-29",
      body: "Is rate of Ethereum (ETH) overbought?",
      tags: "Ethereum Price Prediction|ETH",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "ETH|TRADING",
      source_info: {
        name: "U.Today",
        img: "https://images.cryptocompare.com/news/default/utoday.png",
        lang: "EN",
      },
      source: "utoday",
    },
    {
      id: "23860888",
      guid: "https://www.cryptopolitan.com/?p=474540",
      published_on: 1709222400,
      imageurl: "https://resources.cryptocompare.com/news/43/23860888.jpeg",
      title:
        "AAVE and MANTA Holders Aim for Exciting Price Action in Coming Weeks, but Rebel Satoshi May Have Full Market Attention",
      url: "https://www.cryptopolitan.com/aave-and-manta-holders-aim-for-exciting-price-action-in-coming-weeks-but-rebel-satoshi-may-have-full-market-attention/",
      body: "TLDR The best altcoins such as AAVE and Manta Network (MANTA) have failed to keep up with the surging market. Meanwhile, Rebel Satoshi ($RBLZ) has emerged as the best crypto to buy as it approaches the end of the presale. Let’s understand why experts prefer $RBLZ ahead of top altcoins like AAVE and Manta Network",
      tags: "Sponsored News",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "AAVE|ALTCOIN|BTC|MARKET|TRADING",
      source_info: {
        name: "Cryptopolitan",
        img: "https://images.cryptocompare.com/news/default/cryptopolitan.png",
        lang: "EN",
      },
      source: "cryptopolitan",
    },
    {
      id: "23855605",
      guid: "https://coingape.com/?p=183294",
      published_on: 1709222354,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title:
        "KuCoin Partners Revolut for Euro On-Ramp Amid Bitcoin’s Splendid Rally",
      url: "https://coingape.com/kucoin-partners-revolut-for-euro-on-ramp-amid-bitcoins-splendid-rally/",
      body: "KuCoin, a leading cryptocurrency exchange, has forged a strategic alliance with Revolut, a prominent financial technology company, to enable users to seamlessly purchase digital assets using euros. This partnership marks a significant milestone in the cryptocurrency space, as it provides users with a convenient avenue to acquire various cryptocurrencies listed on KuCoin directly through Revolut The post KuCoin Partners Revolut for Euro On-Ramp Amid Bitcoin’s Splendid Rally appeared first on CoinGape .",
      tags: "24/7 Cryptocurrency News|Bitcoin (BTC) Price|kucoin|Kucoin news",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "BTC|FIAT|TRADING|EXCHANGE|TECHNOLOGY",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23860784",
      guid: "https://en.coin-turk.com/?p=133684",
      published_on: 1709222275,
      imageurl: "https://resources.cryptocompare.com/news/79/23860784.jpeg",
      title:
        "Bitcoin Surpasses $60,000: A Look at Today’s Crypto Market Dynamics",
      url: "https://en.coin-turk.com/bitcoin-surpasses-60000-a-look-at-todays-crypto-market-dynamics/",
      body: "Bitcoin finds buyers above $60,000, a first since 2021 ATH. U.S. Continue Reading: Bitcoin Surpasses $60,000: A Look at Today’s Crypto Market Dynamics",
      tags: "Cryptocurrency News",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "BTC|MARKET",
      source_info: {
        name: "CoinTurk News",
        img: "https://resources.cryptocompare.com/news/79/default.png",
        lang: "EN",
      },
      source: "cointurken",
    },
    {
      id: "23860787",
      guid: "https://www.cryptopolitan.com/?p=475247",
      published_on: 1709222274,
      imageurl: "https://resources.cryptocompare.com/news/43/23860787.jpeg",
      title:
        "Crypto analysts forecast Altcoins frenzy – Get ready to diversify",
      url: "https://www.cryptopolitan.com/crypto-analysts-forecast-altcoins-frenzy/",
      body: "Crypto analysts and experts are currently forecasting an imminent altseason, a period where alternative cryptocurrencies (altcoins) experience significant price surges, particularly as Bitcoin maintains its position above the $62,000 mark. This anticipation is fueled by several factors. Let’s have a look. Altcoins takeover is inevitable As Bitcoin surges to a fresh two-year high, altcoins are",
      tags: "Industry News|News|altcoins|bitcoin|Crypto exploits",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "ALTCOIN|BTC|TRADING",
      source_info: {
        name: "Cryptopolitan",
        img: "https://images.cryptocompare.com/news/default/cryptopolitan.png",
        lang: "EN",
      },
      source: "cryptopolitan",
    },
    {
      id: "23860763",
      guid: "https://cryptonews.com/?p=175186",
      published_on: 1709222271,
      imageurl: "https://resources.cryptocompare.com/news/52/23860763.jpeg",
      title:
        "Dogecoin Price Prediction as Elon Musk Says He’s Returning to the ‘Meme Grindstone’ – Can Meme Coins 100x From Here?",
      url: "https://cryptonews.com/news/dogecoin-price-prediction-as-elon-musk-says-hes-returning-to-the-meme-grindstone-can-meme-coins-100x-from-here.htm",
      body: 'The Dogecoin price has rocketed by 30% in the past 24 hours, after tech entrepreneur Elon Musk tweeted that that he would "get back on the meme grindstone soon". The post Dogecoin Price Prediction as Elon Musk Says He’s Returning to the ‘Meme Grindstone’ – Can Meme Coins 100x From Here? appeared first on Cryptonews .',
      tags: "Price Predictions|Dogecoin|Elon Musk|Meme Coins",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "DOGE|TRADING|TECHNOLOGY",
      source_info: {
        name: "cryptonews",
        img: "https://images.cryptocompare.com/news/default/cryptonews.png",
        lang: "EN",
      },
      source: "cryptonews",
    },
    {
      id: "23855290",
      guid: "https://coingape.com/?post_type=blog&p=183287",
      published_on: 1709222230,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title: "Dogecoin Hits New High: Will DOGE Price Reach $1?",
      url: "https://coingape.com/blog/dogecoin-hits-new-high-will-doge-price-reach-1/",
      body: "Dogecoin (DOGE) skyrockets to new heights, marking the beginning of a parabolic rally. In just the past day, its trading volume has surged by an outstanding 203%, pushing its value to $0.127. This impressive increase cements Dogecoin’s position as the top performer among major digital assets, outpacing the competition in percentage gains. Surpassing its previous The post Dogecoin Hits New High: Will DOGE Price Reach $1? appeared first on CoinGape .",
      tags: "Blog|DOGE $1|Doge price Analysis|DOGE Price Rally|Dogecoin price Analysis",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "DOGE|TRADING",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23860737",
      guid: "https://en.coin-turk.com/?p=133681",
      published_on: 1709222217,
      imageurl: "https://resources.cryptocompare.com/news/79/23860737.jpeg",
      title:
        "Ethereum Developers Propose Maximum Stake Increase from 32 to 2048 ETH",
      url: "https://en.coin-turk.com/ethereum-developers-propose-maximum-stake-increase-from-32-to-2048-eth/",
      body: "Dogecoin sees a 30% price surge, sparking optimism. Whale Alert data shows 761.2 million DOGE moved. Continue Reading: Ethereum Developers Propose Maximum Stake Increase from 32 to 2048 ETH",
      tags: "Dogecoin (DOGE)",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "ETH|DOGE|TRADING",
      source_info: {
        name: "CoinTurk News",
        img: "https://resources.cryptocompare.com/news/79/default.png",
        lang: "EN",
      },
      source: "cointurken",
    },
    {
      id: "23860735",
      guid: "https://en.coin-turk.com/?p=133678",
      published_on: 1709222162,
      imageurl: "https://resources.cryptocompare.com/news/79/23860735.jpeg",
      title: "XRP Price Surge: Can It Reach $1 Again?",
      url: "https://en.coin-turk.com/xrp-price-surge-can-it-reach-1-again/",
      body: "XRP is a major topic in the cryptocurrency world today. An analyst recently suggested XRP could target $1. Continue Reading: XRP Price Surge: Can It Reach $1 Again?",
      tags: "Ripple (XRP)",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "XRP|TRADING",
      source_info: {
        name: "CoinTurk News",
        img: "https://resources.cryptocompare.com/news/79/default.png",
        lang: "EN",
      },
      source: "cointurken",
    },
    {
      id: "23855176",
      guid: "https://coingape.com/?p=183276",
      published_on: 1709222124,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title:
        "Bitcoin Grabs Spotlight On Chinese Social Media Apps Amid Rally To $64K",
      url: "https://coingape.com/bitcoin-news-btc-grabs-spotlight-on-chinese-social-media-apps-amid-rally-to-64k/",
      body: "The recent surge in the value of Bitcoin has captured the attention of internet users in mainland China, despite the government’s strict ban on cryptocurrency activities. Bitcoin (BTC), the world’s largest cryptocurrency, experienced a significant increase of over 21% in the past five days, reaching $64,000 on Thursday. Bitcoin Is Trending On Chinese Social Media The post Bitcoin Grabs Spotlight On Chinese Social Media Apps Amid Rally To $64K appeared first on CoinGape .",
      tags: "24/7 Cryptocurrency News|Bitcoin News|Bitcoin|Bitcoin (BTC) Price|Bitcoin adoption|China crypto",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "BTC|TRADING|ASIA",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "15903966",
      guid: "https://www.cryptopolitan.com/?p=349665",
      published_on: 1709221881,
      imageurl: "https://resources.cryptocompare.com/news/43/15903966.jpeg",
      title: "Rollbit Price Prediction 2024-2033:  Is It Time To Buy RLB?",
      url: "https://www.cryptopolitan.com/rollbit-price-prediction/",
      body: "Rollbit coin price prediction 2024-2033 Rollbit has quickly become one of the most popular crypto casinos and trading platforms. Launched in 2019, Rollbit offers a wide range of gaming, sports betting, futures trading, and NFT options for users. With no KYC requirements and support for numerous cryptocurrencies, Rollbit provides an easy entry into the world",
      tags: "Crypto Price Predictions|cryptocurrency|cryptocurrency trading|cryptomarket",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "TRADING",
      source_info: {
        name: "Cryptopolitan",
        img: "https://images.cryptocompare.com/news/default/cryptopolitan.png",
        lang: "EN",
      },
      source: "cryptopolitan",
    },
    {
      id: "23860619",
      guid: "https://www.cryptopolitan.com/?p=475246",
      published_on: 1709221757,
      imageurl: "https://resources.cryptocompare.com/news/43/23860619.jpeg",
      title:
        "Embracing Diversity in Final Fantasy 7 Rebirth: A LGBTQ+ Perspective",
      url: "https://www.cryptopolitan.com/final-fantasy-7-rebirth-a-lgbtq-perspective/",
      body: "Final Fantasy 7 Rebirth, LGBTQ+ representation thrives, promising a satisfying experience for players. Unlike its predecessor, Rebirth boldly navigates queer narratives, defying traditional norms within the RPG landscape. One notable aspect is the nuanced portrayal of Cloud and Sephiroth’s relationship. Their interactions brim with suggestive undertones throughout the game, challenging typical gender dynamics. A scene",
      tags: "Reviews|Gaming|Gaming Reviews",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "OTHER",
      source_info: {
        name: "Cryptopolitan",
        img: "https://images.cryptocompare.com/news/default/cryptopolitan.png",
        lang: "EN",
      },
      source: "cryptopolitan",
    },
    {
      id: "23860595",
      guid: "https://cryptodaily.co.uk/2024/02/4-cryptos-set-to-skyrocket-this-weekend",
      published_on: 1709221742,
      imageurl: "https://resources.cryptocompare.com/news/75/23860595.jpeg",
      title: "4 Cryptos Set to Skyrocket This Weekend",
      url: "https://cryptodaily.co.uk/2024/02/4-cryptos-set-to-skyrocket-this-weekend",
      body: "Are you ready for the weekend crypto boom? Analysts are buzzing about Ethereum's rally sparking a massive altcoin season, with 4 coins set to potentially skyrocket! Dive into the market's latest dynamics and discover which cryptocurrencies could multiply your investment overnight!",
      tags: "Breaking News",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "ALTCOIN|ETH|MARKET|TRADING",
      source_info: {
        name: "Crypto Daily",
        img: "https://resources.cryptocompare.com/news/75/default.png",
        lang: "EN",
      },
      source: "cryptodaily",
    },
    {
      id: "23860509",
      guid: "https://cryptonews.com/?p=175112",
      published_on: 1709221513,
      imageurl: "https://resources.cryptocompare.com/news/52/23860509.jpeg",
      title:
        "Solana Price Prediction as Daily Trading Volume Blasts Past $8 Billion – Is the Supercycle Here?",
      url: "https://cryptonews.com/news/solana-price-prediction-as-daily-trading-volume-blasts-past-8-billion-is-the-supercycle-here.htm",
      body: "SOL has jumped by 15% in the past 24 hours, with the Solana price racing to $130 as Bitcoin ETF volumes continue to push the cryptocurrency market from one bullish peak to another. The post Solana Price Prediction as Daily Trading Volume Blasts Past $8 Billion – Is the Supercycle Here? appeared first on Cryptonews .",
      tags: "Price Predictions|Altcoins|Price Prediction|Solana",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "TRADING|SOL|ALTCOIN|BTC|MARKET",
      source_info: {
        name: "cryptonews",
        img: "https://images.cryptocompare.com/news/default/cryptonews.png",
        lang: "EN",
      },
      source: "cryptonews",
    },
    {
      id: "23860555",
      guid: "https://u.today/ethereum-eth-whale-nets-over-100-million-in-profits-amid-price-rally",
      published_on: 1709221500,
      imageurl: "https://resources.cryptocompare.com/news/64/23860555.jpeg",
      title:
        "Ethereum (ETH) Whale Nets Over $100 Million in Profits Amid Price Rally",
      url: "https://u.today/ethereum-eth-whale-nets-over-100-million-in-profits-amid-price-rally",
      body: "Ethereum sees growing trend of large-scale accumulation amid price rally",
      tags: "Ethereum News|ETH",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "ETH|TRADING",
      source_info: {
        name: "U.Today",
        img: "https://images.cryptocompare.com/news/default/utoday.png",
        lang: "EN",
      },
      source: "utoday",
    },
    {
      id: "23850007",
      guid: "https://coingape.com/?p=183183",
      published_on: 1709221429,
      imageurl: "https://images.cryptocompare.com/news/default/coingape.png",
      title:
        "Spot Bitcoin ETF Notes Largest Net Inflow of $673 Million on Supply Shock",
      url: "https://coingape.com/spot-bitcoin-etf-notes-largest-net-inflow-677-million-on-supply-shock/",
      body: "Spot Bitcoin ETFs recorded another staggering inflow on Wednesday, breaking the record of the largest inflow of $673 million since launch last month. It follows amid a massive BTC price rally towards ATH due to demand outpacing supply creating a “supply shock“. Bitcoin ETFs Saw $673 Million in Net Inflow Spot Bitcoin exchange-traded funds (ETF) The post Spot Bitcoin ETF Notes Largest Net Inflow of $673 Million on Supply Shock appeared first on CoinGape .",
      tags: "24/7 Cryptocurrency News|Bitcoin News|Bitcoin (BTC) Price|Bitcoin ETF|Spot Bitcoin ETF",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "BTC|TRADING",
      source_info: {
        name: "CoinGape",
        img: "https://images.cryptocompare.com/news/default/coingape.png",
        lang: "EN",
      },
      source: "coingape",
    },
    {
      id: "23860433",
      guid: "https://en.bitcoinsistemi.com/analysts-bitcoin-fever-reignited-parabolic-rally-has-begun-it-is-very-difficult-to-set-a-target-for-the-top-in-btc/",
      published_on: 1709221326,
      imageurl: "https://resources.cryptocompare.com/news/81/23860433.jpeg",
      title:
        'Analysts: "Bitcoin Fever Reignited, Parabolic Rally Has Begun! It is Very Difficult to Set a Target for the Top in BTC!"',
      url: "https://en.bitcoinsistemi.com/analysts-bitcoin-fever-reignited-parabolic-rally-has-begun-it-is-very-difficult-to-set-a-target-for-the-top-in-btc/",
      body: 'Analysts said that the rise in Bitcoin will continue. Will the parabolic rally in BTC continue? here are the details... Continue Reading: Analysts: "Bitcoin Fever Reignited, Parabolic Rally Has Begun! It is Very Difficult to Set a Target for the Top in BTC!"',
      tags: "Analysis|Bitcoin|News",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "BTC|TRADING|MARKET",
      source_info: {
        name: "BitcoinSistemi",
        img: "https://resources.cryptocompare.com/news/81/default.png",
        lang: "EN",
      },
      source: "bitcoinsistemi",
    },
    {
      id: "23860411",
      guid: "https://cryptonews.com/?p=175235",
      published_on: 1709221251,
      imageurl: "https://resources.cryptocompare.com/news/52/23860411.jpeg",
      title: "Bitcoin Miners’ Reserves Drops to Lowest Level Since 2021",
      url: "https://cryptonews.com/news/bitcoin-miners-reserves-drops-to-lowest-level-since-2021.htm",
      body: "Bitcoin (BTC) miners are offloading part of their assets as they look towards the upcoming halving amid increased market activity. The post Bitcoin Miners’ Reserves Drops to Lowest Level Since 2021 appeared first on Cryptonews .",
      tags: "Bitcoin News|Bitcoin|ETF|Miners",
      lang: "EN",
      upvotes: "0",
      downvotes: "0",
      categories: "BTC|MARKET",
      source_info: {
        name: "cryptonews",
        img: "https://images.cryptocompare.com/news/default/cryptonews.png",
        lang: "EN",
      },
      source: "cryptonews",
    },
  ];

  useEffect(() => {
    setCryptoCurrenciesNews({
      data: mockNews,
      filterdData: mockNews,
    });
  }, []);

  const filterData = (e) => {
    const value = e.target.value.toLowerCase();
    const data = [...cryptoCurrenciesNews.data];
    const filteredData = data.filter((news) => {
      return (
        news.title.toLowerCase().includes(value) ||
        news.body.toLowerCase().includes(value) ||
        news.tags.toLowerCase().includes(value) ||
        news.categories.toLowerCase().includes(value)
      );
    });
    setCryptoCurrenciesNews({
      ...cryptoCurrenciesNews,
      filterdData: filteredData,
    });
  };

  return (
    <div className="m-5 text-slate-950 dark:text-white">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-5">
        <h1 className="text-3xl font-bold">{t("latestNews")}</h1>
        <div className="relative hidden md:block">
          <div className="absolute inset-y-0 start-0 flex items-center pl-2 pointer-events-none material-icons text-gray-500 dark:text-gray-400">
            search
          </div>
          <input
            type="text"
            onChange={filterData}
            className="pl-9 w-full p-2 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            placeholder={t("search") + "..."}
          />
        </div>
      </div>
      <div className="scrollable-content overflow-y-auto rounded-lg grid gap-4 border-gray-300 dark:border-gray-600 h-[calc(100vh-170px)]">
        <NewsTable news={cryptoCurrenciesNews.filterdData} />
      </div>
    </div>
  );
}
